### ISSUE TITLE
SNOW-828135: 3.0.4 is missing wheel for python 3.9

### ISSUE THREAD

**Issue by jeppe742** [snowflakedb/snowflake-connector-python#1584]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.9.5

2. What operating system and processor architecture are you using?

   Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

3. What are the component versions in the environment (`pip freeze`)?

4. What did you do?

   When trying to install the latest version (3.0.4) of `snowflake-connector-python` I'm unable to find the whl file for python 3.9.
   I'm using poetry to install the latest version of `snowflake-sqlalchemy`, which has defined `snowflake-connector-python = "<4.0.0"` as dependency, which causes the installation to fail.

e.g if you create a poetry project with the following definition

``` toml
[tool.poetry]
name = "snowflake-test"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "snowflake_test"}]

[tool.poetry.dependencies]
python = "^3.9"
snowflake-sqlalchemy = "^1.4.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
and run a `poetry update`, it will resolve `snowflake-connector-python` to `3.0.4`, but is unable to find the file
![image](https://github.com/snowflakedb/snowflake-connector-python/assets/12828495/bdc25beb-4704-4f56-ba4d-47c2c9189287)

![image](https://github.com/snowflakedb/snowflake-connector-python/assets/12828495/2c07647a-b673-4e9b-a5a6-29c960fcb8ba)

5. What did you expect to see?

   latest version should be installable on python 3.9

6. Can you set logging to DEBUG and collect the logs?
