### ISSUE TITLE
Ability to interpolate variables within `config.toml`

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-connector-python#1971]
### Description

When the snow cli creates the `config.toml` it does not interpolate the variables within the attribute values except for `~`.

e.g. 

```toml
default_connection_name="cheatsheets"

[connections]
[connections.cheatsheets]
account = "account-id"
user = "kameshs"
warehouse = "COMPUTE_WH"
schema = "PUBLIC"
authenticator = "SNOWFLAKE_JWT"
private_key_path="$KEYS_DIR/.keys/rsa_key.p8"
```

The `$KEYS_DIR` never gets interpolated while reading the key path.

It will be nice to add variable interpolation support for all attribute values  with in the `config.toml`.

### What is the desired behavior?

Expecting the parsing on `config.toml` expands the variables as needed.

### How would this improve `snowflake-connector-python`?

It will improve the DevX and helps in automation where the automation tools can define their set of ENV variables to be used.
