### ISSUE TITLE
SNOW-2091311: Provide wheel for Windows ARM64

### ISSUE THREAD

**Issue by khmyznikov** [snowflakedb/snowflake-connector-python#2314]
### What is the current behavior?

Unable to install the package from pip.

### What is the desired behavior?

To have [native wheel for WoA](https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/). GitHub Actions now supports win-arm64 for free.

### How would this improve `snowflake-connector-python`?

Due to the library's popularity, a native version for the growing number of Windows on ARM (WoA) devices offers a better user experience

### References and other background

As for today, I see the problem with dependency - cryptography package. But the work is [already going there.](https://github.com/pyca/cryptography/pull/12770)

**Comment by sfc-gh-sghosh** [comment]
Hello @khmyznikov ,

Thanks for raising the feature request, we are looking into it, will update.

Regards,
Sujan

**Comment by khmyznikov** [comment]
@sfc-gh-mmishchenko @sfc-gh-snow-drivers-warsaw-dl good day folks. I just saw the fresh release but I don't see the win_arm64 platform included, is it intentional or accidental? Is there anything left to be done?

**Comment by sfc-gh-dszmolka** [comment]
you're right @khmyznikov , this issue was apparently closed a little bit too soon. We're checking with other Snowflake teams internally to make this available.

**Comment by khmyznikov** [comment]
@sfc-gh-dszmolka what's the current plan? Anything we can help with?

**Comment by sfc-gh-dszmolka** [comment]
At this moment AFAIK no help is needed and we'll keep this thread posted. Thank you for checking in!

**Comment by sfc-gh-fpawlowski** [comment]
Regarding future plans - we are collaborating with the team responsible for our build and release infrastructure to enable Windows on ARM64 (WoA64) wheels. However, there are current limitations due to the platform we use to build and test our drivers before publishing them to PyPI.

At this time, our build platform does not provide Windows on ARM64 node images, which prevents us from running the full internal pipeline required to officially support this environment. Unfortunately, it doesn't seem that such support will be added in the near future.

That said, thanks to [this PR](https://github.com/snowflakedb/snowflake-connector-python/pull/2478), our GitHub Actions **build pipeline** now creates Windows on ARM64 wheels for Python 3.11+ whenever new features are merged into the main branch. This can provide some level of confidence, that the driver should also build successfully in your environment. However, we are still unable to run the full test suite on this platform due to [dependency build issues](https://github.com/snowflakedb/snowflake-connector-python/actions/runs/18400259969/job/52428171152?pr=2574).

Please note that:
1. We currently cannot publish prebuilt WoA64 wheels to PyPI - _pip_ will need to build the package from source on your environment.
2. Since Windows on ARM64 is not yet an officially supported platform, we may not be able to prioritise or guarantee resolution of platform-specific issues encountered when using the driver there.
3. Running [minimal automated testing](https://github.com/snowflakedb/snowflake-connector-python/pull/2574) on Windows ARM64 in Github Actions is pending resolution of toolchain compatibility issues with some dependencies (e.g. _numpy_) - contributions are welcomed.

**Comment by khmyznikov** [comment]
@sfc-gh-fpawlowski the source code for your internal testing pipeline is avaiable? It's possible to reproduce them locally?

**Comment by sfc-gh-fpawlowski** [comment]
Not entirely. However, most tests are being run on Github Actions as well, so if [this PR](https://github.com/snowflakedb/snowflake-connector-python/pull/2574) was passing on GHA we could be quite sure the driver is working on WoA64.

However the main blocker of the official support is no offering of Windows on ARM64 node in our pipeline's cloud environment.

**Comment by khmyznikov** [comment]
@sfc-gh-fpawlowski understood. Who's your cloud provider?

**Comment by khmyznikov** [comment]
@sfc-gh-fpawlowski I see you use aws, azure, gcp. Could you potentially run the windows related tests in azure? Anything we can do to help with that?

**Comment by sfc-gh-fpawlowski** [comment]
Our CI nodes themselves are limited to AWS distribution of Windows AMI arm64.
Therefore, unfortunately, we are blocked until there is such offering available.

However, if you wish to run the Python driver on Windows on ARM64 (by compiling it from source locally for now), we would be more than happy to welcome a PR that updates the Python driver's code to make the tests pass on GitHub Actions on Windows on ARM64 nodes - available for testing in GhA already. This way next releases could include those changes.

**Comment by xieofxie** [comment]
As of today, AWS still does not have arm64 version. I am thinking if we could leverage github actions win arm64 to do that? Copilot gives a path like 
```text
AWS/Jenkins x64
  └─ cross-build win_arm64 wheel
  └─ calculate SHA-256
  └─ upload wheel + manifest to immutable S3 key
  └─ dispatch trusted GitHub workflow
           ↓
GitHub windows-11-arm
  └─ assume read-only AWS role using OIDC
  └─ download exact S3 object version
  └─ verify SHA-256
  └─ install wheel without rebuilding
  └─ run ARM64 tests
           ↓
Jenkins
  └─ wait for GitHub run result
  └─ verify tested digest matches candidate
  └─ publish that same S3 object
```

<details>
<summary>Click to expand details</summary>


## 1. Jenkins creates an immutable candidate

Use a content-addressed S3 path rather than overwriting `latest`:

```powershell
$wheel = Get-ChildItem dist\*win_arm64.whl | Select-Object -First 1
$sha256 = (Get-FileHash $wheel.FullName -Algorithm SHA256).Hash.ToLower()
$key = "python-connector/windows-arm64/$env:GIT_COMMIT/$sha256/$($wheel.Name)"

aws s3 cp $wheel.FullName "s3://sfc-release-candidates/$key"
```

Enable S3 versioning, ideally Object Lock, and record:

```json
{
  "commit": "abc123...",
  "filename": "snowflake_connector_python-4.8.0-cp313-cp313-win_arm64.whl",
  "sha256": "012345...",
  "s3_key": "python-connector/windows-arm64/abc123/012345/...whl",
  "s3_version_id": "..."
}
```

The version ID prevents an object from being replaced between testing and publication.

## 2. Jenkins dispatches a trusted workflow

The workflow should exist on `main`; Jenkins passes data as inputs rather than executing workflow code from the candidate branch.

```yaml
name: Validate Windows ARM64 release candidate

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        required: true
        type: string
      s3_key:
        required: true
        type: string
      s3_version_id:
        required: true
        type: string
      wheel_sha256:
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  checks: write

jobs:
  validate:
    runs-on: windows-11-arm
    environment: windows-arm64-release-validation
    steps:
      # Use commit-pinned action SHAs in the production workflow.
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Verify release commit
        shell: pwsh
        run: |
          git fetch origin main
          git merge-base --is-ancestor HEAD origin/main
          if ($LASTEXITCODE -ne 0) {
            throw "Candidate commit is not contained in main"
          }

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::ACCOUNT:role/github-windows-arm-candidate-reader
          aws-region: us-west-2

      - name: Download exact candidate
        shell: pwsh
        run: |
          aws s3api get-object `
            --bucket sfc-release-candidates `
            --key '${{ inputs.s3_key }}' `
            --version-id '${{ inputs.s3_version_id }}' `
            candidate.whl

      - name: Verify candidate checksum
        shell: pwsh
        run: |
          $actual = (Get-FileHash candidate.whl -Algorithm SHA256).Hash.ToLower()
          $expected = '${{ inputs.wheel_sha256 }}'.ToLower()
          if ($actual -ne $expected) {
            throw "Wheel checksum mismatch: expected $expected, received $actual"
          }

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install exact wheel
        shell: pwsh
        run: |
          python -m pip install --only-binary=:all: --no-deps .\candidate.whl
          python -c "import platform; assert platform.machine().upper() == 'ARM64'"
          python -c "import snowflake.connector; print(snowflake.connector.__version__)"

      - name: Install test dependencies
        run: python -m pip install -r test-requirements.txt

      - name: Run Windows ARM64 tests
        run: python -m tox run -e py313-unit-parallel
```

The installation should use the wheel directly and prohibit fallback source builds. Adapt the test environment to the repository’s actual tox targets.

Jenkins dispatches it through a narrowly scoped GitHub App installation token:

```text
POST /repos/snowflakedb/snowflake-connector-python/
     actions/workflows/validate-windows-arm64.yml/dispatches
```

with:

```json
{
  "ref": "main",
  "inputs": {
    "commit_sha": "abc123...",
    "s3_key": "python-connector/windows-arm64/abc123/012345/package.whl",
    "s3_version_id": "s3-version-id",
    "wheel_sha256": "012345..."
  }
}
```

## 3. Give GitHub read-only S3 access

Do not pass AWS keys or a presigned URL through workflow inputs. Configure GitHub OIDC with an IAM role restricted to:

- This repository.
- A protected GitHub environment such as `windows-arm64-release-validation`.
- `s3:GetObject` and `s3:GetObjectVersion` only.
- The release-candidate prefix only.
- No upload, deletion, or PyPI publication permissions.

The trust relationship should constrain the OIDC subject to the repository/environment:

```json
{
  "Effect": "Allow",
  "Principal": {
    "Federated": "arn:aws:iam::ACCOUNT:oidc-provider/token.actions.githubusercontent.com"
  },
  "Action": "sts:AssumeRoleWithWebIdentity",
  "Condition": {
    "StringEquals": {
      "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
      "token.actions.githubusercontent.com:sub":
        "repo:snowflakedb/snowflake-connector-python:environment:windows-arm64-release-validation"
    }
  }
}
```

## 4. Gate publication on the GitHub result

The workflow-dispatch API returns the run ID. Jenkins should:

1. Poll that specific run until completion.
2. Require `conclusion == success`.
3. Confirm its recorded inputs contain the expected commit, S3 version ID, and digest.
4. Copy the **same versioned S3 object** into the publishing stage.
5. Publish it without rebuilding.

The digest should be the release identity:

```text
AWS candidate SHA-256
    == GitHub-tested SHA-256
    == PyPI-uploaded SHA-256
```

This avoids duplicate ARM testing. AWS performs the controlled cross-build, GitHub supplies the native ARM64 execution environment, and the release gate proves that the published wheel is byte-for-byte the wheel GitHub tested. Existing AWS AMD64 tests should remain because they validate a different platform artifact.
